<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="gendata" nsURI="http://www.upb.de/lina/cfg/gendata" nsPrefix="gendata">
  <eClassifiers xsi:type="ecore:EClass" name="GeneratorData">
    <eOperations name="getFilteredAddresses" upperBound="-1" eType="#//AddressMapping">
      <eParameters name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="program" eType="ecore:EClass ../../de.upb.llvm_parser/src-gen/de/upb/llvm_parser/LLVM.ecore#//LLVM"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cfgs" lowerBound="1" upperBound="-1"
        eType="ecore:EClass ../../de.upb.lina.cfg/model/ControlFlow.ecore#//ControlFlowDiagram"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
        eType="#//ConstraintMapping" containment="true" eOpposite="#//ConstraintMapping/generatorData"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="locationLabels" upperBound="-1"
        eType="#//LocationLabel" containment="true" eOpposite="#//LocationLabel/generatorData"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitionLabels" upperBound="-1"
        eType="#//TransitionLabel" containment="true" eOpposite="#//TransitionLabel/generatorData"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transformationSpecificKeys"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="phiMappings" upperBound="-1"
        eType="#//PhiMapping" containment="true" eOpposite="#//PhiMapping/generatorData"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filteredAddresses" upperBound="-1"
        eType="#//FilterToAddressMapping" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="addressMappings" upperBound="-1"
        eType="#//AddressMapping" eOpposite="#//AddressMapping/generatorData"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="memorySizeMappings" upperBound="-1"
        eType="#//MemorySizeMapping" containment="true" eOpposite="#//MemorySizeMapping/generatorData"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputTypes" upperBound="-1"
        eType="#//InputTypeList" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="oldToNewCfgName" upperBound="-1"
        eType="#//OldToNewCfgNameMapping" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="globalVariables" upperBound="-1"
        eType="ecore:EClass ../../de.upb.lina.cfg/model/ControlFlow.ecore#//Variable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allVariables" upperBound="-1"
        eType="ecore:EClass ../../de.upb.lina.cfg/model/ControlFlow.ecore#//Variable"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AddressMapping" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="adresses" upperBound="-1"
        eType="ecore:EClass ../../de.upb.llvm_parser/src-gen/de/upb/llvm_parser/LLVM.ecore#//Address"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="oldNames" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generatorData" eType="#//GeneratorData"
        eOpposite="#//GeneratorData/addressMappings"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstraintMapping">
    <eStructuralFeatures xsi:type="ecore:EReference" name="transition" eType="ecore:EClass ../../de.upb.lina.cfg/model/ControlFlow.ecore#//Transition"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generatorData" eType="#//GeneratorData"
        eOpposite="#//GeneratorData/constraints"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocationLabel" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="controlFlowLocation" eType="ecore:EClass ../../de.upb.lina.cfg/model/ControlFlow.ecore#//ControlFlowLocation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generatorData" eType="#//GeneratorData"
        eOpposite="#//GeneratorData/locationLabels"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TransitionLabel" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="transition" eType="ecore:EClass ../../de.upb.lina.cfg/model/ControlFlow.ecore#//Transition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generatorData" eType="#//GeneratorData"
        eOpposite="#//GeneratorData/transitionLabels"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PhiMapping">
    <eStructuralFeatures xsi:type="ecore:EReference" name="transition" eType="ecore:EClass ../../de.upb.lina.cfg/model/ControlFlow.ecore#//Transition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="phi" upperBound="-1" eType="ecore:EClass ../../de.upb.llvm_parser/src-gen/de/upb/llvm_parser/LLVM.ecore#//Phi"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="blockLabelToUse" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generatorData" eType="#//GeneratorData"
        eOpposite="#//GeneratorData/phiMappings"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FilterToAddressMapping" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" upperBound="-1"
        eType="#//AddressMapping"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MemorySizeMapping">
    <eStructuralFeatures xsi:type="ecore:EReference" name="instruction" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generatorData" eType="#//GeneratorData"
        eOpposite="#//GeneratorData/memorySizeMappings"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="completeTypeSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="warning" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="offset" upperBound="-1"
        eType="#//OffsetElement" containment="true" eOpposite="#//OffsetElement/memorySizeMapping"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputTypeList">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inputType" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OldToNewCfgNameMapping" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OffsetElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="factor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variableValue" eType="ecore:EClass ../../de.upb.llvm_parser/src-gen/de/upb/llvm_parser/LLVM.ecore#//Value"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="intValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="constant" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="memorySizeMapping" eType="#//MemorySizeMapping"
        eOpposite="#//MemorySizeMapping/offset"/>
  </eClassifiers>
</ecore:EPackage>
