/**
 *
 * $Id$
 */
package de.upb.llvm_parser.llvm.validation;

import de.upb.llvm_parser.llvm.TypeUse;
import de.upb.llvm_parser.llvm.Value;

/**
 * A sample validator interface for {@link de.upb.llvm_parser.llvm.Branch}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BranchValidator {
	boolean validate();

	boolean validateDestination(Value value);
	boolean validateCondvalue(Value value);
	boolean validateLabelTruetype(TypeUse value);
	boolean validateLabelTrue(Value value);
	boolean validateLabelFalsetype(TypeUse value);
	boolean validateLabelFalse(Value value);
}
