/**
 *
 * $Id$
 */
package de.upb.llvm_parser.llvm.validation;

import de.upb.llvm_parser.llvm.Address;
import de.upb.llvm_parser.llvm.FunctionBody;
import de.upb.llvm_parser.llvm.ParameterList;
import de.upb.llvm_parser.llvm.TypeList;
import de.upb.llvm_parser.llvm.TypeUse;

/**
 * A sample validator interface for {@link de.upb.llvm_parser.llvm.FunctionDefinition}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FunctionDefinitionValidator {
	boolean validate();

	boolean validateReturnType(TypeUse value);
	boolean validateAddress(Address value);
	boolean validatePl(ParameterList value);
	boolean validateBody(FunctionBody value);
	boolean validateTList(TypeList value);
}
