/**
 *
 * $Id$
 */
package de.upb.llvm_parser.llvm.validation;

import de.upb.llvm_parser.llvm.Address;
import de.upb.llvm_parser.llvm.ParameterList;
import de.upb.llvm_parser.llvm.TypeUse;
import de.upb.llvm_parser.llvm.Value;

/**
 * A sample validator interface for {@link de.upb.llvm_parser.llvm.Invoke}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface InvokeValidator {
	boolean validate();

	boolean validateFunctiontype(TypeUse value);
	boolean validateName(Address value);
	boolean validatePList(ParameterList value);
	boolean validateTotype(TypeUse value);
	boolean validateTovalue(Value value);
	boolean validateUnwindtype(TypeUse value);
	boolean validateUnwindvalue(Value value);
}
