/**
 *
 * $Id$
 */
package de.upb.llvm_parser.llvm.validation;

import de.upb.llvm_parser.llvm.TypeList;
import de.upb.llvm_parser.llvm.TypeUse;
import de.upb.llvm_parser.llvm.Value;

import java.math.BigDecimal;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link de.upb.llvm_parser.llvm.Store}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface StoreValidator {
	boolean validate();

	boolean validateNewtype(TypeUse value);
	boolean validateTypes(EList<TypeList> value);
	boolean validateNewvalue(Value value);
	boolean validateAdresstype(TypeUse value);
	boolean validateAdress(Value value);
	boolean validateOrdering(String value);
	boolean validateIndex(BigDecimal value);
}
