/**
 *
 * $Id$
 */
package de.upb.llvm_parser.llvm.validation;

import de.upb.llvm_parser.llvm.Address;
import de.upb.llvm_parser.llvm.Structure;

/**
 * A sample validator interface for {@link de.upb.llvm_parser.llvm.TypeDefinition}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TypeDefinitionValidator {
	boolean validate();

	boolean validateAddress(Address value);
	boolean validateStruct(Structure value);
}
