/*
 * generated by Xtext
 */
package de.upb.llvm_parser.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import de.upb.llvm_parser.ui.internal.LLVMActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class LLVMExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return LLVMActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return LLVMActivator.getInstance().getInjector(LLVMActivator.DE_UPB_LLVM_PARSER_LLVM);
	}
	
}
