/*
* generated by Xtext
*/
package de.upb.lina.lll.ui.contentassist;

import de.upb.lina.lll.ui.contentassist.AbstractExpressionsProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class ExpressionsProposalProvider extends AbstractExpressionsProposalProvider {

}
