/*
* generated by Xtext
*/
package de.upb.llvm_parser.ui.contentassist;

import de.upb.llvm_parser.ui.contentassist.AbstractLLVMProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class LLVMProposalProvider extends AbstractLLVMProposalProvider {

}
