<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="llvm" nsURI="http://www.upb.de/llvm_parser/llvm" nsPrefix="llvm">
  <eClassifiers xsi:type="ecore:EClass" name="LLVM">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//AbstractElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="TopLevelEntity" eSuperTypes="#//AbstractElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="module" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="target" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="libs" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MainLevelEntity" eSuperTypes="#//AbstractElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionHeader" eSuperTypes="#//MainLevelEntity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="returnType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pList" eType="#//ParameterList"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//FunctionBody"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tList" eType="#//TypeList"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeList">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="types" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Aggregate">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="agg" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocalVar" eSuperTypes="#//MainLevelEntity #//Instruction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instr" eType="#//Instruction"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alias" eType="#//Alias"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Alias">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//TypeAndValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aliasee" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeAndValue" eSuperTypes="#//Clause #//Resume">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregate" eType="#//Aggregate"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GetElementPtr" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pointer" upperBound="-1"
        eType="#//TypeAndValue" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="params" upperBound="-1"
        eType="#//TypeAndValue" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExtractValue" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregate" eType="#//Aggregate"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="index" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InsertValue" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregate" eType="#//Aggregate"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//TypeAndValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="index" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fence" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ordering" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CmpXchg" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="adress" eType="#//TypeAndValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="compare_val" eType="#//TypeAndValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="new_val" eType="#//TypeAndValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ordering" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AtomicRMW" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="adress" eType="#//TypeAndValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//TypeAndValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ordering" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Load" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="adress" eType="#//TypeAndValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="align" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="index" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ordering" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Store" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//TypeAndValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="adress" eType="#//TypeAndValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ordering" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="index" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Call" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pointer" eType="#//TypeAndValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="plist" eType="#//ParameterList"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Alloc" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="numElements" eType="#//TypeAndValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="params" upperBound="-1"
        eType="#//TypeAndValue" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PHI" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1"
        eType="#//ValuePair" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValuePair" eSuperTypes="#//Compare #//ARITHMETIC_OP #//LOGICAL_OP">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LandingPad" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="personality" eType="#//TypeAndValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="clause" upperBound="-1"
        eType="#//Clause" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="personalitytype" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="personalityfunction" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="castto" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Clause">
    <eStructuralFeatures xsi:type="ecore:EReference" name="filter" upperBound="-1"
        eType="#//TypeAndValue" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Select" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//TypeAndValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="val1" eType="#//TypeAndValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="val2" eType="#//TypeAndValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VA_Arg" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="list" eType="#//TypeAndValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="argType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExtractElement" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="vector" eType="#//TypeAndValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="index" eType="#//TypeAndValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InsertElement" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="vector" eType="#//TypeAndValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scalar" eType="#//TypeAndValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="index" eType="#//TypeAndValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ShuffleVector" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="vector1" eType="#//TypeAndValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vector2" eType="#//TypeAndValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mask" eType="#//TypeAndValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cast" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//TypeAndValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="castto" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Compare" eSuperTypes="#//Instruction"/>
  <eClassifiers xsi:type="ecore:EClass" name="ARITHMETIC_OP" eSuperTypes="#//Instruction"/>
  <eClassifiers xsi:type="ecore:EClass" name="LOGICAL_OP" eSuperTypes="#//Instruction"/>
  <eClassifiers xsi:type="ecore:EClass" name="Instruction"/>
  <eClassifiers xsi:type="ecore:EClass" name="IndirectBranch" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="adress" eType="#//TypeAndValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lList" eType="#//LabelList"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LabelList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="labels" upperBound="-1"
        eType="#//TypeAndValue" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Switch" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//TypeAndValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="default" eType="#//TypeAndValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="jTable" eType="#//JumpTable"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JumpTable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1"
        eType="#//TypeAndValue" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="destinations" upperBound="-1"
        eType="#//TypeAndValue" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Invoke" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="function" eType="#//TypeAndValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pList" eType="#//ParameterList"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" eType="#//TypeAndValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="unwind" eType="#//TypeAndValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Resume" eSuperTypes="#//Instruction"/>
  <eClassifiers xsi:type="ecore:EClass" name="Unreachable" eSuperTypes="#//Instruction"/>
  <eClassifiers xsi:type="ecore:EClass" name="Return" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//TypeAndValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Branch" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="destination" eType="#//TypeAndValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cond" eType="#//TypeAndValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="labelTrue" eType="#//TypeAndValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="labelFalse" eType="#//TypeAndValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionBody">
    <eStructuralFeatures xsi:type="ecore:EReference" name="blocks" upperBound="-1"
        eType="#//BasicBlock" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BasicBlock">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instructions" upperBound="-1"
        eType="#//Instruction" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
