/*
* generated by Xtext
*/
package de.upb.llvm_parser;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class LLVMUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return de.upb.llvm_parser.ui.internal.LLVMActivator.getInstance().getInjector("de.upb.llvm_parser.LLVM");
	}
	
}
