<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="lowlevellang" nsURI="http://www.upb.de/lina/lll/lowlelvellang"
    nsPrefix="lowlevellang">
  <eClassifiers xsi:type="ecore:EClass" name="Program">
    <eStructuralFeatures xsi:type="ecore:EReference" name="functions" upperBound="-1"
        eType="#//Function" eOpposite="#//Function/program"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="globalVars" eType="#//Variable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Function" eSuperTypes="platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//ENamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="program" eType="#//Program"
        eOpposite="#//Program/functions"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameter" upperBound="-1"
        defaultValueLiteral="">
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
        <eTypeArguments eClassifier="#//Value"/>
        <eTypeArguments eClassifier="#//Type"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="localVars" upperBound="-1"
        eType="#//Variable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="labels" upperBound="-1"
        eType="#//Label" eOpposite="#//Label/function"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instructions" upperBound="-1"
        eType="#//Instruction" eOpposite="#//Instruction/function"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Label" abstract="true" eSuperTypes="platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//ENamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="function" eType="#//Function"
        eOpposite="#//Function/labels"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instruction" eType="#//Instruction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetregister" eType="#//Variable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="function" eType="#//Function"
        eOpposite="#//Function/instructions"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="instruction" eType="#//InstructionEnum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AtomicRMW" eSuperTypes="#//Trinary">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" eType="#//AtomicEnum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArithmeticOperation" eSuperTypes="#//Trinary">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" eType="#//ArithmeticEnum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Call" eSuperTypes="#//Unary">
    <eStructuralFeatures xsi:type="ecore:EReference" name="function" eType="#//Function"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameter">
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList">
        <eTypeArguments eClassifier="#//Value"/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Compare" eSuperTypes="#//Trinary">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" eType="#//CompareEnum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConditionalBranch" eSuperTypes="#//Unary">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="ecore:EClass LLL_Expression.ecore#//Expression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trueLabel" eType="#//Label"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="falseLabel" eType="#//Label"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Goto" eSuperTypes="#//Unary">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//Label"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LogicOperation" eSuperTypes="#//Trinary">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" eType="#//LogicEnum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Value" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constant" eSuperTypes="#//Value">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="constant" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable" eSuperTypes="#//Value">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Predefined" abstract="true" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="SelfdefinedType" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PreInteger" eSuperTypes="#//Predefined"/>
  <eClassifiers xsi:type="ecore:EClass" name="PreFloat" eSuperTypes="#//Predefined"/>
  <eClassifiers xsi:type="ecore:EClass" name="Primitive" eSuperTypes="#//Predefined"/>
  <eClassifiers xsi:type="ecore:EEnum" name="LogicEnum"/>
  <eClassifiers xsi:type="ecore:EEnum" name="ArithmeticEnum"/>
  <eClassifiers xsi:type="ecore:EEnum" name="InstructionEnum">
    <eLiterals name="Alloca"/>
    <eLiterals name="Return" value="1"/>
    <eLiterals name="Load" value="2"/>
    <eLiterals name="Store" value="3"/>
    <eLiterals name="Fence" value="4"/>
    <eLiterals name="CompareAndSwap" value="5"/>
    <eLiterals name="Cast" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CompareEnum"/>
  <eClassifiers xsi:type="ecore:EClass" name="Unary" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="param1" eType="#//Value"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Binary" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="param2" eType="#//Value"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="param1" eType="#//Value"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Trinary" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="param3" eType="#//Value"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="param2" eType="#//Value"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="param1" eType="#//Value"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AtomicEnum"/>
</ecore:EPackage>
