/**
 *
 * $Id$
 */
package de.upb.lina.lll.validation;

import de.upb.lina.lll.Instruction;
import de.upb.lina.lll.Label;
import de.upb.lina.lll.Program;
import de.upb.lina.lll.Type;
import de.upb.lina.lll.VariableOrValue;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link de.upb.lina.lll.Function}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FunctionValidator {
	boolean validate();

	boolean validateProgram(Program value);
	boolean validateLocalVariablesOrValues(EList<VariableOrValue> value);
	boolean validateLabels(EList<Label> value);
	boolean validateInstructions(EList<Instruction> value);
	boolean validateInputParameters(EList<VariableOrValue> value);

	boolean validateReturnType(Type value);
}
