/**
 *
 * $Id$
 */
package de.upb.lina.lll.validation;

import de.upb.lina.lll.Label;

import de.upb.lina.lll.expressions.LExpression;

/**
 * A sample validator interface for {@link de.upb.lina.lll.ConditionalBranch}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ConditionalBranchValidator {
	boolean validate();

	boolean validateElseTarget(Label value);
	boolean validateCondition(LExpression value);
}
