/**
 *
 * $Id$
 */
package de.upb.lina.lll.validation;

import de.upb.lina.lll.Function;
import de.upb.lina.lll.Variable;
import de.upb.lina.lll.VariableOrValue;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link de.upb.lina.lll.Instruction}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface InstructionValidator {
	boolean validate();

	boolean validateInstructionResult(Variable value);
	boolean validateFunction(Function value);
	boolean validateParameters(EList<VariableOrValue> value);
}
